### ISSUE TITLE
Next 12 and 13

### ISSUE THREAD

**Issue by galago** [ChuckJonas/next-ssl-redirect-middleware#4]
Seems middleware has changed for the new versions. Any idea how to make this package work in the more recent versions? 

Following the new structure adding the middleware to root/middleware.ts 

I get this runtime error 

`requestUrl.searchParams.keys is not a function or its return value is not iterable`

**Comment by karlbecker** [comment]
Just a heads up that it seems to be working fine for me on Next 13.5.6.

**Comment by ChuckJonas** [comment]
same
