### ISSUE TITLE
Fresh NextJS app - failed to build

### ISSUE THREAD

**Issue by alilland** [ChuckJonas/next-ssl-redirect-middleware#5]
using "next": "13.4.2" im getting a build error

```
$ npm run build

> steppingstonesinternational@0.1.0 build
> next build

- info Linting and checking validity of types  
Failed to compile.

./node_modules/next/dist/compiled/@vercel/og/index.node.js
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/next-ssl-redirect-middleware/dist/index.js
./src/pages/_middleware.ts


> Build failed because of webpack errors
- info Creating an optimized production build .% 
```

this looks like its because its depending on next/server, but really i have no clue how to fix it. I've been stuck in reactjs 16 for a long time, so nextjs is a new topic for me.

**Comment by ChuckJonas** [comment]
this lib has no dependencies on `fs` so not sure why thats being referenced...

It might be how nextjs is trying to load your middleware.  You should be using `middleware.ts` now, not `pages/_middleware.ts`.  See [the docs](https://nextjs.org/docs/app/building-your-application/routing/middleware)
