### ISSUE TITLE
Comma separated X-Forwarded-Proto

### ISSUE THREAD

**Issue by SystemDisc** [ChuckJonas/next-ssl-redirect-middleware#8]
My `X-Forwarded-Proto` is being set to `https,http`, which causes an redirect to the same page over and over, leading to the browser error of "too many redirects". I think the condition should be `!req.headers.get('x-forwarded-proto')?.startsWith('https')`

**Comment by SystemDisc** [comment]
It looks like the code already uses `!req.headers?.get("x-forwarded-proto")?.includes("https")` which will work, but there was no closing parenthesis for the if statement, and the code in the NPM package is still `req.headers.get("x-forwarded-proto") !== "https"`

**Comment by ChuckJonas** [comment]
ah that explains why there was a new version (I ran `npm publish` and the build failed).  Should be live in `0.1.5`
